/**
 * Wide-gamut export: ExportService converts sRGB -> target in linear light and
 * the writer attaches the matching bundled ICC profile (assets/icc/*.icc,
 * generated by scripts/gen-icc-profiles.cjs). 16-bit + wide-gamut downgrades to
 * 8-bit (sharp's rgb16 + ICC re-transforms pixels) but stays correctly tagged.
 */
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { ExportService } from '../services/ExportService';

const { writeImageFile } = require('../../electron/imageWriter.cjs');
const sharp = require('sharp');

const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'photo-widegamut-test-'));
afterAll(() => { try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch { /* ignore */ } });

function pack(pixels: number[][], TypedArray: typeof Uint8Array | typeof Uint16Array): ArrayBuffer {
  const arr = new TypedArray(pixels.length * 4);
  pixels.forEach((p, i) => { arr[i * 4] = p[0]; arr[i * 4 + 1] = p[1]; arr[i * 4 + 2] = p[2]; arr[i * 4 + 3] = p[3]; });
  return arr.buffer;
}

describe('ExportService.convertColorSpace (sRGB -> wide gamut)', () => {
  const svc = new ExportService();
  const convert = (data: Float32Array, to: string): Float32Array =>
    (svc as unknown as { convertColorSpace(d: Float32Array, w: number, h: number, from: string, to: string): Float32Array })
      .convertColorSpace(data, 2, 1, 'srgb', to);

  test.each(['adobergb', 'prophoto', 'rec2020'])('%s keeps neutral gray neutral, stays in range, preserves alpha', (space) => {
    const data = new Float32Array([0.5, 0.5, 0.5, 1, 1, 0, 0, 0.5]);
    const out = convert(data, space);
    // Neutral gray stays neutral (white->white matrix).
    expect(Math.abs(out[0] - out[1])).toBeLessThan(0.005);
    expect(Math.abs(out[1] - out[2])).toBeLessThan(0.005);
    // All colour channels remain in [0,1].
    for (let i = 0; i < out.length; i++) {
      if (i % 4 !== 3) { expect(out[i]).toBeGreaterThanOrEqual(0); expect(out[i]).toBeLessThanOrEqual(1); }
    }
    // Alpha untouched.
    expect(out[3]).toBe(1);
    expect(out[7]).toBe(0.5);
    // sRGB red moves inside the wider gamut (less saturated): R<1 and G/B small.
    expect(out[4]).toBeLessThan(1);
  });

  test('unknown target returns input unchanged', () => {
    const data = new Float32Array([0.3, 0.6, 0.9, 1]);
    const out = convert(data, 'rec709-bogus');
    expect(Array.from(out)).toEqual(Array.from(data));
  });
});

describe('imageWriter wide-gamut profile attach', () => {
  const corners8 = [[219, 0, 0, 255], [100, 150, 200, 255], [0, 0, 0, 255], [255, 255, 255, 255]];

  test('8-bit AdobeRGB export attaches an ICC profile and preserves the pixels', async () => {
    const out = path.join(tmpDir, 'adobe8.png');
    await writeImageFile(out, pack(corners8, Uint8Array), 'png', { width: 2, height: 2, channels: 4, bitDepth: 8, colorSpace: 'adobergb' });

    const meta = await sharp(out).metadata();
    expect(meta.icc).toBeTruthy(); // tagged with a profile
    const desc = meta.icc ? meta.icc.toString('latin1') : '';
    expect(desc).toMatch(/Adobe RGB/i);

    // Pixels are NOT re-transformed (already converted upstream) — attach only.
    const { data } = await sharp(out).raw().toBuffer({ resolveWithObject: true });
    expect([data[0], data[1], data[2]]).toEqual([219, 0, 0]);
  });

  test('16-bit wide-gamut downgrades to 8-bit but stays tagged and correct', async () => {
    const corners16 = corners8.map(p => p.map(v => v * 257));
    const out = path.join(tmpDir, 'adobe16.png');
    await writeImageFile(out, pack(corners16, Uint16Array), 'png', { width: 2, height: 2, channels: 4, bitDepth: 16, colorSpace: 'adobergb' });

    const meta = await sharp(out).metadata();
    expect(meta.depth).toBe('uchar');  // downgraded from 16-bit
    expect(meta.icc).toBeTruthy();     // still tagged AdobeRGB
    const { data } = await sharp(out).raw().toBuffer({ resolveWithObject: true });
    expect([data[0], data[1], data[2]]).toEqual([219, 0, 0]);
  });

  test('each wide-gamut space resolves a bundled profile', async () => {
    for (const [space] of [['adobergb'], ['prophoto'], ['rec2020']]) {
      const out = path.join(tmpDir, `${space}.png`);
      await writeImageFile(out, pack(corners8, Uint8Array), 'png', { width: 2, height: 2, channels: 4, bitDepth: 8, colorSpace: space });
      const meta = await sharp(out).metadata();
      expect(meta.icc).toBeTruthy();
    }
  });
});
