// AUTO-GENERATED by scripts/gen-icc-profiles.cjs - do not edit by hand.
// Linear-light sRGB -> target 3x3 matrices + target TRC gamma, kept consistent
// with the embedded ICC profiles in assets/icc/.
export interface ColorSpaceConversion {
  gamma: number;
  srgbToLinearTarget: number[][];
  file: string;
}
export const COLOR_SPACE_CONVERSIONS: Record<string, ColorSpaceConversion> = {
  "adobergb": {
    "gamma": 2.19921875,
    "srgbToLinearTarget": [
      [
        0.7151256068556247,
        0.28487439314437574,
        0
      ],
      [
        -5.323432666903827e-17,
        1.0000000000000002,
        -2.0816681711721685e-17
      ],
      [
        6.938893903907228e-18,
        0.04116194845011842,
        0.958838051549882
      ]
    ],
    "file": "AdobeRGB1998.icc"
  },
  "prophoto": {
    "gamma": 1.8,
    "srgbToLinearTarget": [
      [
        0.5292769776226114,
        0.3301545019784931,
        0.14056852039889553
      ],
      [
        0.09836585954044914,
        0.8734707129069618,
        0.02816342755258903
      ],
      [
        0.016875340921386813,
        0.11765941425612081,
        0.8654652448224924
      ]
    ],
    "file": "ProPhoto.icc"
  },
  "rec2020": {
    "gamma": 2.4,
    "srgbToLinearTarget": [
      [
        0.627403895934699,
        0.32928303837788375,
        0.043313065687417274
      ],
      [
        0.06909728935823199,
        0.919540395075459,
        0.011362315566309154
      ],
      [
        0.016391438875150228,
        0.08801330787722578,
        0.895595253247624
      ]
    ],
    "file": "Rec2020.icc"
  }
};
