/**
 * UserStyleProfile
 *
 * AUTO-GENERATED by scripts/extract_style_profile.py — do not edit by hand.
 * Re-run the script after grading more photos:
 *
 *   python scripts/extract_style_profile.py \
 *     --portfolio "<your-portfolio-folder>" \
 *     --out src/services/UserStyleProfile.ts
 *
 * Generated:   2026-06-05 22:31:14 UTC
 * Source:      <your-portfolio-folder>
 * Photo count: 200 processed
 *
 * AutoAdjustService imports this module and uses the bucket-appropriate
 * profile as targets for its autoXxx() methods. selectBucket() chooses
 * which profile applies based on the current image's ImageStats.
 */

export type BucketName = 'standard' | 'warm' | 'cool' | 'low_light' | 'high_key';

export interface StyleProfile {
  sampleCount: number;
  targetMedianLum: number;
  targetMeanLum: number;
  targetStdLum: number;
  targetMeanSat: number;
  targetP5: number;
  targetP25: number;
  targetP75: number;
  targetP95: number;
  targetTonalSpan: number;
  acceptableShadowMeanLum: number;
  acceptableHighlightMeanLum: number;
  shadowPixelRatio: number;
  highlightPixelRatio: number;
  rbRatio: number;
}

export interface BucketSelectorStats {
  mean_lum: number;
  rb_ratio: number;
}

/**
 * Choose the bucket whose grading characteristics best fit the current image.
 * Order of tests matches scripts/extract_style_profile.py:bucket_of().
 */
export function selectBucket(stats: BucketSelectorStats): BucketName {
  if (stats.mean_lum < 0.20) return 'low_light';
  if (stats.mean_lum > 0.62) return 'high_key';
  if (stats.rb_ratio > 1.15 && stats.mean_lum < 0.55) return 'warm';
  if (stats.rb_ratio < 0.88) return 'cool';
  return 'standard';
}

export const userStyleProfile: Record<BucketName, StyleProfile> = {
  standard: {
    sampleCount: 65,
    targetMedianLum:            0.4166,
    targetMeanLum:              0.4259,
    targetStdLum:               0.2391,
    targetMeanSat:              0.2601,
    targetP5:                   0.0589,
    targetP25:                  0.2232,
    targetP75:                  0.6577,
    targetP95:                  0.8263,
    targetTonalSpan:            0.747,
    acceptableShadowMeanLum:    0.1347,
    acceptableHighlightMeanLum: 0.8252,
    shadowPixelRatio:           0.2887,
    highlightPixelRatio:        0.1476,
    rbRatio:                    1.0388,
  },
  warm: {
    sampleCount: 101,
    targetMedianLum:            0.3308,
    targetMeanLum:              0.3709,
    targetStdLum:               0.2074,
    targetMeanSat:              0.3933,
    targetP5:                   0.0552,
    targetP25:                  0.1844,
    targetP75:                  0.5225,
    targetP95:                  0.7428,
    targetTonalSpan:            0.685,
    acceptableShadowMeanLum:    0.1354,
    acceptableHighlightMeanLum: 0.8309,
    shadowPixelRatio:           0.3682,
    highlightPixelRatio:        0.0471,
    rbRatio:                    1.5275,
  },
  cool: {
    sampleCount: 9,
    targetMedianLum:            0.4423,
    targetMeanLum:              0.4608,
    targetStdLum:               0.2423,
    targetMeanSat:              0.4322,
    targetP5:                   0.0843,
    targetP25:                  0.3095,
    targetP75:                  0.6292,
    targetP95:                  0.8779,
    targetTonalSpan:            0.7695,
    acceptableShadowMeanLum:    0.1508,
    acceptableHighlightMeanLum: 0.8366,
    shadowPixelRatio:           0.1829,
    highlightPixelRatio:        0.1308,
    rbRatio:                    0.6522,
  },
  low_light: {
    sampleCount: 14,
    targetMedianLum:            0.0655,
    targetMeanLum:              0.1513,
    targetStdLum:               0.1691,
    targetMeanSat:              0.4255,
    targetP5:                   0.0069,
    targetP25:                  0.0254,
    targetP75:                  0.2038,
    targetP95:                  0.5384,
    targetTonalSpan:            0.5345,
    acceptableShadowMeanLum:    0.0705,
    acceptableHighlightMeanLum: 0.8053,
    shadowPixelRatio:           0.8115,
    highlightPixelRatio:        0.0107,
    rbRatio:                    2.0302,
  },
  high_key: {
    sampleCount: 11,
    targetMedianLum:            0.9163,
    targetMeanLum:              0.8897,
    targetStdLum:               0.1241,
    targetMeanSat:              0.1301,
    targetP5:                   0.5797,
    targetP25:                  0.873,
    targetP75:                  0.9356,
    targetP95:                  0.9468,
    targetTonalSpan:            0.36,
    acceptableShadowMeanLum:    0.1779,
    acceptableHighlightMeanLum: 0.9263,
    shadowPixelRatio:           0.003,
    highlightPixelRatio:        0.8277,
    rbRatio:                    1.0399,
  }
} as const;
